{
 "title": "Xen Prometheus",
 "description": "View XCP-ng (XenServer) metrics collected by https://github.com/MikeDombo/xen-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "VM Hosts",
    "query": {
     "query": "label_values(xen_host_loadavg, host)"
    }
   },
   {
    "name": "vm_uuids",
    "label": "VM Guests",
    "query": {
     "query": "xen_vm_memory{host=~\"$host\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "xen_host_loadavg{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xen_host_cpu{host=~\"$host\"}",
     "legendFormat": "cpu{{cpu}} - {{host}}"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xen_vm_memory{host=~\"$host\"} - (xen_vm_memory_internal_free{host=~\"$host\"} * 1024)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "VM CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(vm) (xen_vm_cpu{host=~\"$host\"})",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "xen_host_pif_rx{pif=\"aggr\",host=~\"$host\"}",
     "legendFormat": "rx - {{host}}"
    },
    {
     "expr": "xen_host_pif_tx{pif=\"aggr\",host=~\"$host\"}",
     "legendFormat": "tx - {{host}}"
    }
   ]
  },
  {
   "title": "VM Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "xen_vm_vif_rx{host=~\"$host\"}",
     "legendFormat": "rx {{vm}}"
    },
    {
     "expr": "xen_vm_vif_tx{host=~\"$host\"}",
     "legendFormat": "tx {{vm}}"
    }
   ]
  },
  {
   "title": "SR Read/Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "xen_host_io_throughput_read{host=~\"$host\"}",
     "legendFormat": "Read {{sr}} - {{host}}"
    },
    {
     "expr": "xen_host_io_throughput_write{host=~\"$host\"}",
     "legendFormat": "Write {{sr}} - {{host}}"
    }
   ]
  },
  {
   "title": "VM IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "xen_vm_vbd_io_throughput_read{host=~\"$host\"}",
     "legendFormat": "Read {{vm}} /{{vbd}} - {{host}}"
    },
    {
     "expr": "xen_vm_vbd_io_throughput_write{host=~\"$host\"}",
     "legendFormat": "Write {{vm}} /{{vbd}} - {{host}}"
    }
   ]
  },
  {
   "title": "VM IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "xen_vm_vbd_latency{host=~\"$host\"}",
     "legendFormat": "{{vm}} /{{vbd}} - {{host}}"
    }
   ]
  },
  {
   "title": "Collector Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "xen_collector_duration_seconds", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "$vm_uuids",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "vm_uuids",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "xen_vm_cpu{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "cpu{{cpu}}"
      }
     ]
    },
    {
     "title": "VM Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "xen_vm_memory{vm_uuid=\"$vm_uuids\"} - (xen_vm_memory_internal_free{vm_uuid=\"$vm_uuids\"} * 1024)",
       "legendFormat": "Memory used"
      }
     ]
    },
    {
     "title": "VM Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "xen_vm_vif_rx{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "rx {{vif}}"
      },
      {
       "expr": "xen_vm_vif_tx{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "tx {{vif}}"
      }
     ]
    },
    {
     "title": "VM IO Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "xen_vm_vbd_io_throughput_read{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "Read {{vbd}}"
      },
      {
       "expr": "xen_vm_vbd_io_throughput_write{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "Write {{vbd}}"
      }
     ]
    },
    {
     "title": "VM IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "xen_vm_vbd_iops_read{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "Read {{vbd}}"
      },
      {
       "expr": "xen_vm_vbd_iops_write{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "Write {{vbd}}"
      }
     ]
    },
    {
     "title": "VM Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "xen_vm_vbd_read_latency{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "Read {{vbd}}"
      },
      {
       "expr": "xen_vm_vbd_write_latency{vm_uuid=\"$vm_uuids\"}",
       "legendFormat": "Write {{vbd}}"
      }
     ]
    }
   ]
  }
 ]
}